---
# Requires: ansible-galaxy collection install kubernetes
# Note: community.kubernetes.helm is moving to kubernetes.core
- hosts: controllers[0]
  collections:
    - kubernetes.core
  vars:
    namespace: cattle-system
    hostname: rancher.{{ ansible_ssh_host }}.xip.io
    email: admin@cloudve.org
  tasks:
    - name: Install openshift
      pip:
        name: openshift
        state: present
    - name: Create the {{ namespace }} namespace.
      k8s:
        name: "{{ namespace }}"
        kind: Namespace
    - name: Install the helm repo
      helm_repository:
        name: rancher
        repo_url: https://releases.rancher.com/server-charts/stable
    - name: Install Rancher
      helm:
        name: rancher
        namespace: "{{ namespace }}"
        chart_ref: rancher/rancher
        values:
          hostname: "{{ hostname }}"
          ingress:
            tls:
              source: letsEncrypt
          letsEncrypt:
            email: "{{ email }}"
            environment: production
            ingress:
              class: nginx
      tags: [ never, rancher ]
    - name:
      debug:
        msg: The Rancher dashboard should be available at https://{{ hostname }} in a few minutes.

